name: Run Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hunternise/splines:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run pytest
        run: |
          export PYTHONPATH="${PYTHONPATH}:./"
          pytest -q tests
